name: React Native CLI Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          ls -d node_modules/expo-modules-autolinking/android/expo-gradle-plugin || echo "Plugin dir missing!"

      - name: Build Android Release
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          cd android
          echo "Android directory: $(pwd)"
          ls -la
          sed -i 's/\r$//' gradlew || echo "sed failed"
          chmod +x gradlew || echo "chmod failed"
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
